"""add friend table

Revision ID: 4dc35353cdf5
Revises: 563cc1498942
Create Date: 2024-01-03 18:35:26.691846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc35353cdf5'
down_revision: Union[str, None] = '563cc1498942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peer_1', sa.Integer(), nullable=True),
    sa.Column('peer_2', sa.Integer(), nullable=True),
    sa.CheckConstraint('peer_1 != peer_2', name='check_peer_ids_different'),
    sa.ForeignKeyConstraint(['peer_1'], ['user.id'], ),
    sa.ForeignKeyConstraint(['peer_2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend')
    # ### end Alembic commands ###
